### PR TITLE
Added pwntools

### PR DESCRIPTION
**Pull request by mosajjal**
Works fine.

### CODE REVIEW

**Comment by koep** [comment]
Isn't this an exact copy of the official pwntools Dockerfile (except the maintainer tag) https://hub.docker.com/r/pwntools/pwntools/~/dockerfile/?

I don't really see the benefit of having it in this repo. Or am I missing somethin @mosajjal ?

**Comment by mosajjal** [comment]
Yes it's the exact same. I've pulled it here to have it as a collection in this repository. Just like mitmproxy that I've added

**Comment by koep** [comment]
Okay, I think @jessfraz should decide if this adds value to this repo!

**Comment by jessfraz** [comment]
Hi, this is awesome! and thanks for taking the time to open this! If I'm not using an image ~weekly or all the time, I feel badly maintaining it, mostly because I won't know if it will break or not.
I'm also not exactly an official library and the cool thing about docker is anyone can publish any images they want. So I am going to pass, sorry! But thank you!

**Pull request closed without merging**
