### PR TITLE
fix gtk version for tor version 8

### PR DESCRIPTION
**Pull request by florianwe**
seems like its no longer dependent on gtk2 but gtk3 instead

### CODE REVIEW

**Comment by florianwe** [comment]
#409 is the problem you will encounter if you don't update gtk to 3. The update will fix it. I've tested it and it works for me.

**Comment by koep** [comment]
Thanks @florianwe!

**Comment by jessfraz** [comment]
thanks!!

**Comment by florianwe** [comment]
np

**Pull request merged**
