### PR TITLE
Replaced deprecated MAINTAINER with LABEL

### PR DESCRIPTION
**Pull request by michael-k**
Used format proposed in https://docs.docker.com/engine/reference/builder/#maintainer-deprecated

### CODE REVIEW

**Comment by jessfraz** [comment]
Thanks for taking the time to do this!

**Comment by michael-k** [comment]
`sed` for the win :)

**Comment by jamesmstone** [comment]
Hey @michael-k, you don't happen to have that `sed` command handy ! I could find it quite useful

**Comment by michael-k** [comment]
@jamesmstone Example: `sed -i 's/MAINTAINER Jessie Frazelle <jess@linux.com>/LABEL maintainer "Jessie Frazelle <jess@linux.com>"/g' **/Dockerfile`

**Pull request merged**
