### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by MichaelBitard**

### CODE REVIEW

**Comment by jessfraz** [comment]
is this really a typo its referring to the built image on docker hub?

**Comment by jessfraz** [comment]
ah its here: https://hub.docker.com/r/jess/keepassxc/

**Comment by MichaelBitard** [comment]
Yes, that's what my change is for :+1:

**Comment by jessfraz** [comment]
oh dope sorry

**Comment by jessfraz** [comment]
thanks!

**Pull request merged**
