### PR TITLE
FreeMind v1.0.1 added

### PR DESCRIPTION
**Pull request by loadaverage**
[FreeMind](http://freemind.sourceforge.net/wiki/index.php/Main_Page) is a premier free mind-mapping software written in Java. The recent development has hopefully turned it into high productivity tool. We are proud that the operation and navigation of FreeMind is faster than that of MindManager because of one-click "fold / unfold" and "follow link" operations.

### CODE REVIEW

**Comment by koep** [comment]
I like FreeMind very much! This Image is pretty large though.

Just out of curiosity: Did you look into using the https://hub.docker.com/_/openjdk/ Alpine version as base image? FreeMind seems to be a simple Java app.

**Comment by jessfraz** [comment]
yay alpine!

**Comment by TechGym** [comment]
Jess, I really enjoyed reading your blog!  Thanks for sharing!  I am new to docker but thought your blog would be a great way to get started.  Any advice?

**Comment by loadaverage** [comment]
@jessfraz Alpine in action

**Comment by jessfraz** [comment]
Hi sorry, I try to keep these all maintained and only add ones I personally use so I am going to close this but your dockerfile is great and you should make a repo to house them for yourself :)

**Pull request closed without merging**
