### PR TITLE
Update start.sh

### PR DESCRIPTION
**Pull request by gschaetz**
Don't know if they changed it or what but it is now editor not code

### CODE REVIEW

**Comment by jessfraz** [comment]
is this a troll is this actually going to start `ed` :)

**Comment by gschaetz** [comment]
No I just ran it and it opened vscode =)  Promise!

**Comment by gschaetz** [comment]
but that would be funny

**Comment by jessfraz** [comment]
thanks and yes I loled thinking about it hahaha

**Comment by gschaetz** [comment]
Sorry if this is a bother but I built a github repo that leverages your dockerfiles on an automated desktop. The repo is gschaetz/desktop-ansible.  It allows for automated setup of a desktop where all the apps are running in docker using your images mainly:) Just thought you may be interested in it. The project still has a way to go...

**Pull request merged**
