### PR TITLE
Update PowerShell version to beta 8

### PR DESCRIPTION
**Pull request by jahands**
This updates PowerShell to the latest release from https://github.com/PowerShell/PowerShell/releases

### CODE REVIEW

**Comment by jahands** [comment]
Looks like this deb is bad. Fails locally on WSL as well. Jumped the gun on this one.

**Comment by jahands** [comment]
I just realized they changed the naming of releases. Fixing...

**Comment by jahands** [comment]
It [builds for me now](https://i.jha.sh/vmjjc.png).

**Comment by jessfraz** [comment]
Yayyy thanks

**Pull request merged**
